"""Tests for NPC dreams (SoulVoiceLLM.dream_line / dream_one).

Dreams ride the sleep cycle the way HERS ride her absences: every DREAM_EVERY-th sleep,
the soul's OWN tiny brain dreams one line, seeded by the day's residue (its most salient
memory), run hotter than waking speech. Pinned here: the cadence (not every sleep is a
dreaming sleep), the infant rule (a mind that cannot speak cannot dream), the write-back
(source='dream', so the provenance layer voices it as 'I dreamt it, I think'), and that
the dream is the SOUL's -- generated by its private brain, not a shared voice.
"""


import pytest


pytest.importorskip("torch")

from agent.memory import MemoryStore, attributed
from services.llm import SoulVoiceLLM

LIFE = ("I mend the nets at first light and watch the water for the change.\n"
        "The saltmarsh smells of iron after rain and the gulls know it first.\n"
        "My father taught me the knots and the patience between them.\n") * 6


class _Soul:
    def __init__(self, sid="s0"):
        self.id, self.persona = sid, "You are Cael the fisher."
        self.memory = MemoryStore(seed=5)
        for i, ln in enumerate(dict.fromkeys(LIFE.splitlines())):
            self.memory.write(ln, tick=i, source="self")


def test_infants_do_not_dream(tmp_path):
    router = SoulVoiceLLM(minds_dir=str(tmp_path))
    soul = _Soul()
    router.mind_for(soul.id)                      # born, never slept
    assert router.dream_line(soul.id, "the water") == ""
    assert router.dream_one(soul, tick=1) is None


def _insist(dream_fn, tries=6):
    # dream generation SAMPLES a young stochastic brain: any single draw may come out
    # under the too-thin floor (that is dream_line working as designed, not a defect).
    # The claims under test are about cadence/privacy/write-back, not sampling luck --
    # so ask a few times. (This exact test flaked twice before this guard existed.)
    for _ in range(tries):
        d = dream_fn()
        if d:
            return d
    return ""


def test_the_dream_cadence_and_write_back(tmp_path):
    import torch
    torch.manual_seed(0)
    router = SoulVoiceLLM(minds_dir=str(tmp_path))
    soul = _Soul()
    mind = router.mind_for(soul.id)
    mind.sleep(LIFE, steps=12)                    # one real (short) sleep -> it can speak
    assert mind.sleeps == 1
    assert router.dream_line(soul.id, "the water") == ""      # sleep 1: no dream yet
    mind.sleeps = 2
    assert router.dream_line(soul.id, "the water") == ""      # sleep 2: still none
    mind.sleeps = 3                                            # the third sleep dreams
    before = len(soul.memory.items)
    dream = _insist(lambda: router.dream_one(soul, tick=99))
    assert dream and isinstance(dream, str)
    dreamt = [m for m in soul.memory.items if m.source == "dream"]
    assert len(dreamt) == 1 or len(soul.memory.items) == before   # written new, or merged
    if dreamt:
        assert dreamt[0].speaker_id == soul.id     # the soul's OWN dream
        # the provenance layer voices it as a dream at recall (§5.19)
        assert "(I dreamt it, I think)" in attributed(dreamt[0])


def test_dreams_are_private_to_their_brain(tmp_path):
    router = SoulVoiceLLM(minds_dir=str(tmp_path))
    a, b = _Soul("sA"), _Soul("sB")
    for soul in (a, b):
        mind = router.mind_for(soul.id)
        mind.sleep(LIFE, steps=12)
        mind.sleeps = router.DREAM_EVERY          # both due to dream
    da = _insist(lambda: router.dream_line(a.id, "the water"))
    db = _insist(lambda: router.dream_line(b.id, "the water"))
    assert da and db                              # both dream...
    # ...from DIFFERENT brains (fresh inits differ; identical dreams would mean a
    # shared mind wearing two names)
    assert router.mind_for(a.id) is not router.mind_for(b.id)
